// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProductCatalog;

#nullable disable

namespace ProductCatalog.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<int>("Cost")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "cost");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ca173802-206e-4a88-a6cc-2ac93e590fba"),
                            Cost = 100,
                            Name = "Футболка"
                        },
                        new
                        {
                            Id = new Guid("304e34b1-5267-433a-8d7d-a0abd761da11"),
                            Cost = 200,
                            Name = "Шорты"
                        },
                        new
                        {
                            Id = new Guid("35e52d12-62f8-4451-ab81-b549fa3f066b"),
                            Cost = 50,
                            Name = "Носки"
                        },
                        new
                        {
                            Id = new Guid("388ea4e6-f760-4735-9aa5-e3df9906b49c"),
                            Cost = 70,
                            Name = "Трусы"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
